version: '3.7'

services:
  app:
    build: ./app
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./app/src:/app/src
      - ./app/public:/app/public
  api:
    build: ./api
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./api/cmd:/root/cmd
      - ./api/pkg:/root/pkg
      - ./data:/root/data