version: '3.7'

services:
  app:
    container_name: app_container
    hostname: app
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - 80:80
    environment:
      - API_ORIGIN=http://berlin-chat.soon.it:8080
  api:
    container_name: api_container
    hostname: api
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - 8080:8080
