version: '3.7'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - 80:80
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - 8080:8080
