version: '3.7'

services:
  app:
    build: ./app
    restart: always
  api:
    build: ./api
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./api/cmd:/root/cmd
      - ./api/pkg:/root/pkg
