version: '3.7'

services:
  app:
    build: ./app/Dockerfile.prod
    restart: always
    ports:
      - 80:80
  api:
    build: ./api/Dockerfile.prod
    restart: always
    ports:
      - 8080:8080
