# build environment
FROM arm32v7/node:12-alpine as builder
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install
COPY . .
RUN yarn build

# production environment
FROM arm32v7/nginx:1.17.9
WORKDIR /root

# install brotli nginx module
RUN apt-get update && apt-get upgrade -y
COPY --from=builder /app/build /var/www/berlin-chat/html
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./nginx/healthcheck.sh /bin/healthcheck.sh

EXPOSE 80

HEALTHCHECK CMD ["sh", "/bin/healthcheck.sh"]
