FROM arm32v7/golang:1.13

WORKDIR /root

COPY go.mod .

RUN go mod download

COPY . .

RUN go build -o main ./cmd/main.go

EXPOSE 8080

HEALTHCHECK CMD wget --quiet --tries=1 --spider http://localhost:8080 || exit 1

CMD ["/root/main"]
