name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: get code from repo
      uses: actions/checkout@v2

    - name: ssh into server
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: | 
          echo 'test' > ./test.txt
          echo 'test2' > ./test2.txt
        host: ${{ secrets.HOST }}
        username: deploy
        privateKey: ${{ secrets.SSH_PRIVATE_KEY}}
